### ISSUE TITLE
babel-plugin-s2s-reducer-case-createrが止まります。

### ISSUE THREAD

**Issue by kztmk** [akameco/s2s#156]
* module name: babel-plugin-s2s-reducer-case-creater
* module version: 0.1.9
* `node` version: 8.11.1
* `yarn` version:1.5.1
  

**Do you want report a _bug_?:**
bugかは不明な報告です。

s2s: version 0.18.1

にて、babel-plugin-s2s-reducer-case-createrがエラーで止まります。

$ /Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/.bin/s2s
s2s started monitoring. Enjoy coding with s2s.
babel:s2s-action-types app/containers/someObjectViewPage/actionTypes.js → app/containers/someObjectViewPage/actionTypes.js
babel:s2s-action-creater app/containers/someObjectViewPage/actionTypes.js → app/containers/someObjectViewPage/actions.js
TypeError: /Users/user_home/Documents/Devs/ProjectsRoot/projectName/app/containers/someObjectViewPage/reducer.js: Cannot read property 'filter' of undefined
    at SwitchStatement.items.map.name (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-plugin-s2s-reducer-case-creater/lib/index.js:79:79)
    at Array.map (<anonymous>)
    at SwitchStatement (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-plugin-s2s-reducer-case-creater/lib/index.js:76:42)
    at NodePath._call (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/user_home/Documents/Devs/ProjectsRoot/projectName/node_modules/babel-traverse/lib/path/context.js:115:19)

同じマシンでの別プロジェクト(create-react-appからeject)したものでは問題無く動作します。

何か設定に不備があるのでしょうか？

**Comment by kztmk** [comment]
申し訳ありません。エディタの設定ミスでactionTypes.jsでアクション名の最初が小文字に変換されていました。
