### ISSUE TITLE
initial-state-creater で State type が配列の場合もオブジェクトで初期化される

### ISSUE THREAD

**Issue by elzup** [akameco/s2s#73]
- module name: babel-plugin-s2s-initial-state-creater
- module version:  s2s@0.12.1
- `node` version: v8.9.1
- `yarn` version: 1.3.2

## Relevant code or config 

検証で足したテスト

```javascript
/* packages/babel-plugin-s2s-initial-state-creater/__fixtures__/reducer-mix.js */
// @flow
type Count = number
type Item = { count: Count, isLoading: boolean }
type State = Array<Item>

const initialState: State = []

```

```diff
FAIL  packages/babel-plugin-s2s-initial-state-creater/src/index.test.js
● s2s-initial-state-creater › initialState array

expect(value).toMatchSnapshot()

Received value does not match stored snapshot 1.

- Snapshot
+ Received

@@ -13,7 +13,7 @@
  type Count = number;
  type Item = { count: Count; isLoading: boolean; };
  type State = Item[];

  // $FlowFixMe
- const initialState: State = [];
+ const initialState: State = {};
  "

  at tester (node_modules/babel-plugin-tester/dist/index.js:196:44)
  at Object.<anonymous> (node_modules/babel-plugin-tester/dist/index.js:108:13)
      at Generator.next (<anonymous>)
  at step (node_modules/babel-plugin-tester/dist/index.js:43:191)
  at node_modules/babel-plugin-tester/dist/index.js:43:361
      at <anonymous>
  at process._tickCallback (internal/process/next_tick.js:188:7)

```

## What you did:
initial-state-creater で reducer のinitialState に配列を定義した。

## What happened:
初期化がから配列でなく空オブジェクトとなる。
**別の初期化も空オブジェクト上書きされる。**

## Suggested solution:

State がオブジェクトである reducer のみに適用するべき plugin ですか？その場合各自が target を s2s.config で調整します。

期待する動作
とりあえず配列の場合は変更されない。

**Comment by akameco** [comment]
問題は認識していたんですが、とりあえずでオブジェクトのみ適用するようにしてます。
最終的には、配列およびその他のプリミティブ型で初期化可能にするつもりです。

それまでは、以下のようにオブジェクト型を使う必要があります。           

```js
type State: = { items:  Item[] }
```

今後修正しようと思っていましたが、あなたがPRを送ることも出来ます。
もし、PRを送るのであれば歓迎ですが、どうですか？

**Comment by akameco** [comment]
@elzup これに取り組みます？

**Comment by elzup** [comment]
@akameco 取り組みません。
こちらではとりあえずオブジェクトを使う方法で対応します。

**Comment by akameco** [comment]
対応しました。次回リリースで配列及びプリミティブ型での初期化が可能になります。
